### ISSUE TITLE
Externally updating gives error this.histSlider.update is not a function

### ISSUE THREAD

**Issue by Difusio** [oguzhaninan/vue-histogram-slider#11]
I have got some buttons outside of histogram slider that set the time range on the slider. For example past hour or past day. This used to work and I updated the sliders from property like this:

`this.$refs.histogramSlider.update({from: this.sinceTime})`

However after an update it started throwing the above error and it's not updating anything. The rest of the slider is working as intended.

Am I updating it wrong?

**Comment by oguzhaninan** [comment]
I fixed the issue and released a new version. You can update.

**Comment by Difusio** [comment]
That was fast, thanks. I can see the handles responding now, but they are both jumping to the end of the slider. I'm calling histogramSlider.update with this object:

{from: 1586766807, to: 1585669707}

Should that be working? I have verified that these values lie within the min and max of the slider.

**Comment by oguzhaninan** [comment]
I added an example. There is no problem working now. You can see it [here](https://github.com/oguzhaninan/vue-histogram-slider/blob/master/src/App.vue).
