### ISSUE TITLE
Not rendering on the server side (window exposed)

### ISSUE THREAD

**Issue by melalj** [oguzhaninan/vue-histogram-slider#15]
I'm using nuxt and it's failing as window is exposed to load jquery here: https://github.com/oguzhaninan/vue-histogram-slider/blob/master/src/lib/range-slider.js#L14

If should at least check if window exists :)

**Comment by oguzhaninan** [comment]
Hi @melalj,
Thanks for warning. I fixed this issue. Please check the new version.
