### ISSUE TITLE
Data for histogram

### ISSUE THREAD

**Issue by dinhthang12t** [oguzhaninan/vue-histogram-slider#2]
Hi how can i customize data for histogram like: data: [10,5,4,20,100]
Thank you

**Comment by oguzhaninan** [comment]
Hi @dinhthang12t,
Example:
```vue
<template>
  <div id="app">
    <HistogramSlider
      style="margin: 200px auto"
      :width="600"
      :bar-height="100"
      :data="data"
      :prettify="prettify"
      :drag-interval="true"
      :colors="['#4facfe', '#00f2fe']"
      :min="4"
      :max="100"
    />
  </div>
</template>

<script>
export default {
  data() {
    return {
      data: [10, 5, 4, 20, 100]
    };
  }
};
</script>
```

**Comment by jonalxh** [comment]
Hi @oguzhaninan 
What if the server send me the counted data? Something like this:

[
  { value: 5, count: 15},
  { value: 250, count: 124},
  ...
]

Is there a way to pass the data in this way?

Thanks for your help.

**Comment by oguzhaninan** [comment]
Hi @jonalxh,
There is no structure suitable for this data. You can just take the values ​​and try them out by making a list.

[5, 250,....]

**Comment by jonalxh** [comment]
Ok, I'll try, thanks.
