### ISSUE TITLE
Question: Handle size

### ISSUE THREAD

**Issue by robertjoellewis** [oguzhaninan/vue-histogram-slider#3]
Can I make handle size bigger? It's not super fun on mobile, but I think it would be if the handle size could be changed. Is there already a prop for this?

**Comment by oguzhaninan** [comment]
Hi @robertjoellewis,
There is not a prop for that. But i will add tomorrow. Thank you for your feedback.

**Comment by robertjoellewis** [comment]
Oh wow. That would be amazing. Thank you!

**Comment by oguzhaninan** [comment]
I have add handle-size prop.
