### ISSUE TITLE
How do you use more than one slider on a single component

### ISSUE THREAD

**Issue by ArkturusKayne** [oguzhaninan/vue-histogram-slider#4]
It seems that this slider uses IDs and classes that prevent you from having more than one slider present on the same component at the same time. 

The result is that any sliders created after the first one end up taking up the same space on the page.

How do you prevent this from happening and use more than one slider per page/component?

**Comment by oguzhaninan** [comment]
I will fix it in new version ASAP.

**Comment by negaodanado** [comment]
:+1: UP... could check this out, it would be nice to have multiple instances of sliders!!!

**Comment by SimonCehlin** [comment]
Is this something that will be resolved soon?

**Comment by oguzhaninan** [comment]
I fixed the issue and released a new version.
