### ISSUE TITLE
Using vue-histogram without global registration

### ISSUE THREAD

**Issue by hsks** [oguzhaninan/vue-histogram-slider#51]
The current implementation of vue histogram suggests to register the component globally in the app.
This leads to the components being bundled at places we don't need it.

Also, registering the component locally leads to infinite recursion.

Is there a way we can register the component locally?

**Comment by hsks** [comment]
Never mind. We made it work using a dynamic import. The problem wasn't with the library. We use our app in SSR mode, hence the library couldn't work perfectly when SSR kicked in. This was because we were statically importing the library despite rendering the component specifically on the client side.
A simple client only rendering with dynamic import does the trick. This is because dynamic imports will not be resolved until the component is rendered, hence the import/registration will not be an issue on the server side.

Closing this issue. Thanks a lot for the library!

**Comment by SchneiderOr** [comment]
Can you gently give an example of how you overcome this issue with nuxt? im unable to overcome it with nuxt3
