### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation. on change event

### ISSUE THREAD

**Issue by Kiran-addweb** [oguzhaninan/vue-histogram-slider#6]
I have implemented a slider for price range slider.
![Screenshot 2019-12-30 at 6 25 11 PM](https://user-images.githubusercontent.com/40349600/71582812-c6632680-2b31-11ea-93ab-5a9518ce7ef6.png)
Here I attached the screenshot,
I wanted to update the price value once it changes.
thanks.

**Comment by oguzhaninan** [comment]
Hi @Kiran-addweb,
Could you write your code.

**Comment by kiran-lightcom** [comment]
Hi @oguzhaninan ,
Thanks for reply.
Here is my code and error you can check below.

slider declaration:
```
<histogram-Slider
      style="margin: 0 auto;touch-action: none"
      :width="370"
      :bar-height="0"
      :data="data"
      :drag-interval="true"
      :force-edges="false"
      :colors="['#6B818C', '#A3A5AD']"
      :min="min"
      :max="max"
      @change="onchangeSlider"
    />
```
Data onject :
```
data() {
      return {
        data: [],
        min: 0,
        max: 1000,
        startValue: 0,
        endValue: 150,        
      };
  },
```

Methods :
```
methods: {
    onchangeSlider(values) {
      this.startValue = values.from;
      this.endValue = values.to;
    }
}
```
And finally error screen shot,




![Screenshot from 2020-01-24 11-23-31](https://user-images.githubusercontent.com/59560596/73047998-a4916100-3e9d-11ea-9177-ed7c2f8207bd.png)
Please do needful.
Thanks

**Comment by kiran-lightcom** [comment]
Hi, @oguzhaninan  I have resolved that issue, it happened due to implemented two slider in the same component for mobile and desktop.
If you wanted to resolve the issue if it used twice in the same component then you can check but for mine, I have removed one slider from a component.
