### ISSUE TITLE
Considering a less restrictive license.

### ISSUE THREAD

**Issue by execuc** [oguzhaninan/vue-histogram-slider#8]
This component is very great but I can't use it on a commercial single page application without opening source code. Is it wanted ? Or do you have the possibility to change the license ?

**Comment by oguzhaninan** [comment]
Hi @execuc,
I changed the license. You can use it freely.

**Comment by execuc** [comment]
Thank you very much !

**Comment by sebastian-raubach** [comment]
Thanks for changing this to MIT! Maybe an update to the badge in the README would be good, as I almost dismissed this library because of GPL-v3.
